<?php
// Set the content type to JSON
header('Content-Type: application/json');

// Define a list of blocked keywords
$blocked_keywords = [
  "please join",
  "quick loan",
  "viagra",
  "casino",
  "lottery",
  "free money",
  "win big",
  "click here",
  "buy now",
  "limited time offer",
  "act now",
  "binance",
  "binance account",
  "binance.com",
  "guaranteed",
  "no obligation",
  "risk free",
  "special promotion",
  "all natural",
  "do it today",
  "don't delete",
  "great offer",
  "order now",
  "no questions asked",
  "what are you waiting for?",
  "worried about",
  "no cost",
  "no fees",
  "no catch",
  "no gimmick",
  "no strings attached",
  "no purchase necessary",
  "no hidden fees",
  "no credit card required",
  "no experience necessary",
  "no risk",
  "no investment",
  "no money down",
  "one hundred percent free",
  "one hundred percent guaranteed",
  "one time offer",
  "only $19.99",
  "only $9.99",
  "only available here",
  "outrageous offer",
  "pennies a day",
  "save big money",
  "save up to 50 percent",
  "serious cash",
  "supplies are limited",
  "take action now",
  "time limited offer",
  "urgent",
  "while supplies last",
  "winner",
  "you are a winner!",
  "#1 rated",
  "additional income",
  "best price",
  "best prices",
  "big bucks",
  "billion",
  "cash bonus",
  "cents on the dollar",
  "consolidate debt",
  "double your cash",
  "double your income",
  "earn extra cash",
  "earn money",
  "eliminate bad credit",
  "extra cash",
  "fast cash",
	"financial freedom",
	"free gift",
	"free hosting",
	"free info",
	"free preview",
	"increase sales fast",
	"lower rates",
	"lowest price ever",
	"make money now",
	"million dollars",
	"miracle cure",
	"money back guarantee",
	"once in a lifetime",
	"prize",
	"pure profit",
	"save up to 50%",
	"unsecured credit",
	"work from home",
	"100% guaranteed",
  "100% satisfied",
  "absolutely free",
  "as seen on",
  "be your own boss",
  "become a member",
  "billion dollars",
  "congratulations",
  "debt relief",
  "discount",
  "earn cash",
  "earn money fast",
  "easy money",
  "exclusive deal",
  "extra income",
  "for instant access",
  "free gift",
  "free information",
  "free membership",
  "go viral",
  "hurry up!",
  "increase sales",
  "increase traffic fast",
  "internet business opportunity",
  "investment decision",
  "join millions of people",
  "limited time only!",
  "make money online",
  "make money fast!",
  "money making opportunities",
  "money saving offer",
  "networks marketing",
  "No fees ever!",
  "No hidden charges!",
  "No hidden costs!",
  "No purchase necessary!",
  "No strings attached!",
  "one time only!",
  "one time offer!",
  "online biz opportunity!",
  "online income opportunity!",
  "opportunity of a lifetime!",
  "pay off your mortgage!",
  "Penny stocks!",
  "Pyramid scheme!",
  "promise you will earn money!",
  "pure profit!",
  "risk-free trial",
  "savings account",
  "unsecured loans",
  "unsecured debt",
  "unsecured credit cards",
  "unsecured personal loans",
  "unsecured credit line",
  "unsecured business loans",
  "unsecured credit offers",
  "urgent response needed!",
  "vacation offers",
  "weight loss",
  "winner!",
  "work from home jobs!",
  "you are a winner!",
  "your income",
  "zero investment",
  "172.105.78.244",
  "198.12.243.105",
  "accept credit cards",
  "#1",
  "100% free",
  "100% more",
  "Accept credit cards",
  "Additional income",
  "cephalexin",
  "As seen on",
  "Be your own boss",
  "Become a member",
  "Beneficiary",
  "Billing",
  "Billion",
  "Bulk email",
  "Buy direct",
  "Call now",
  "Cancel at any time",
  "Cards accepted",
  "Cents on the dollar",
  "Certified",
  "Check or money order",
  "Clearance",
  "Click below",
  "Click here",
  "Compare rates",
  "Confidentiality",
  "Congratulations",
  "Consolidate debt",
  "Credit card offers",
  "Direct email",
  "Direct marketing",
  "Do it today",
  "Don’t delete",
  "Don't delete",
  "Double your cash",
  "Double your income",
  "Earn extra cash",
  "Exclusive deal",
  "Expect to earn",
  "Extra cash",
  "Extra income",
  "Fast cash",
  "Free gift",
  "Free hosting",
  "Free info",
  "Free investment",
  "Free membership",
  "Free money",
  "Get out of debt",
  "Get started now",
  "Hidden charges",
  "Human growth hormone",
  "Increase sales",
  "Increase traffic",
  "Incredible deal",
  "Information you requested",
  "Internet marketing",
  "Join millions",
  "Limited time",
  "Lose weight",
  "Lower rates",
  "Lowest price",
  "Make money",
  "Marketing solution",
  "Mass email",
  "Meet singles",
  "Message contains",
  "Million dollars",
  "Money back",
  "Mortgage rates",
  "Multi-level marketing",
  "Name brand",
  "New customers only",
  "No catch",
  "No credit check",
  "No gimmick",
  "No hidden costs",
  "No hidden fees",
  "No interest",
  "No investment",
  "No obligation",
  "No purchase necessary",
  "No questions asked",
  "No strings attached",
  "Not junk",
  "Notspam",
  "Not spam",
  "see for yourself",
  "Once in a lifetime",
  "social security number",
  "Opt in",
  "Order now",
  "Passwords",
  "Pennies a day",
  "Please read",
  "Potential earnings",
  "Pre-approved",
  "Pure profit",
  "Refinance",
  "Requires initial investment",
  "Reserves the right",
  "Risk-free",
  "Save big money",
  "Save up to",
  "Search engine",
  "See for yourself",
  "Sent in compliance",
  "Sign up free",
  "Social security number",
  "Subject to…",
  "Take action",
  "Terms and conditions",
  "This isn’t a scam",
  "This isn’t junk",
  "This isn’t spam",
  "This won’t last",
  "Undisclosed",
  "Unlimited",
  "Unsecured credit",
  "Unsecured debt",
  "Unsolicited",
  "Urgent",
  "Valium",
  "Viagra",
  "Vicodin",
  "Warranty",
  "We hate spam",
  "Web traffic",
  "Weight loss",
  "While supplies last",
  "Will not believe your eyes",
  "Work from home",
  "Xanax",
  "You are a winner",
  "You have been selected",
  "$$$",
  "4u",
  "4-u",
  "additional-income",
  "adipex",
  "advicer",
  "air max",
  "allstate",
  "ambien",
  "baccarrat",
  "BackPage Ads Posting",
  "BackPage Posting",
  "barbour northumbria",
  "blackjack",
  "bllogspot",
  "booker",
  "byob",
  "carisoprodol",
  "car-rental-e-site",
  "car-rentals-e-site",
  "chatroom",
  "cialis",
  "Collect your prize",
  "coolhu",
  "CraigsList Ads Posting",
  "credit-card-debt",
  "credit-report",
  "Cures baldness",
  "cwas",
  "cyclen",
  "cyclobenzaprine",
  "dating-e-site",
  "day-trading",
  "Dear Friend",
  "debt-consolidation",
  "discreetordering",
  "dutyfree",
  "duty-free",
  "Easy date",
  "Email harvest",
  "email-marketing",
  "equityloans",
  "extra-income",
  "fast-cash",
  "Financial Schemes",
  "fioricet",
  "flowers-leading-site",
  "Free gift card",
  "freenet",
  "freenet-shopping",
  "gambling-",
  "hair-loss",
  "health-insurancedeals",
  "holdem",
  "Home based",
  "Home based business",
  "home security systems",
  "homebased",
  "home-based",
  "homeequityloans",
  "homefinance",
  "Hot men",
  "Hot women",
  "hotel-dealse-site",
  "hotele-site",
  "hotelse-site",
  "incest",
  "Income from home",
  "insurancedeals",
  "insurance-quotes",
  "insurnce",
  "jrcreations",
  "Lead generation",
  "levitra",
  "macinstruct",
  "Make $",
  "Marketing solutions",
  "Month trial offer",
  "Mortgage",
  "mortgagequotes",
  "One hundred percent free",
  "-online",
  "Online biz opportunity",
  "Online degree",
  "Online pharmacy",
  "onlinegambling",
  "online-gambling",
  "Opportunity",
  "ottawavalleyag",
  "ownsthis",
  "paxil",
  "penis",
  "Perform in bed",
  "pharmacy",
  "phentermine",
  "poker",
  "poker-chip",
  "poze",
  "pussy",
  "real money",
  "Removes wrinkles",
  "rental-car-e-site",
  "Reverses aging",
  "ringtones",
  "roulette",
  "Score tonight",
  "Search Engine Optimization",
  "seo-",
  "shemale",
  "Shox",
  "sibutramine",
  "Sign-up free today",
  "slot-machine",
  "Social Security Number",
  "Stock alert",
  "Stop snoring",
  "thorcarlson",
  "top-e-site",
  "top-site",
  "tramadol",
  "trim-spa",
  "ultram",
  "University diplomas",
  "Urgent proposal",
  "valeofglamorganconservatives",
  "viagra",
  "vioxx",
  "weightloss",
  "weight-loss",
  "workathome",
  "work-at-home",
  "xanax",
  "You’re a winner",
  "zolus",
  "Abonti",
  "aggregator",
  "AhrefsBot",
  "asterias",
  "BDCbot",
  "BLEXBot",
  "BuiltBotTough",
  "Bullseye",
  "BunnySlippers",
  "ca-crawler",
  "CCBot",
  "Cegbfeieh",
  "CheeseBot",
  "CherryPicker",
  "CherryPickerElite",
  "CherryPickerSE",
  "CopyRightCheck",
  "cosmos",
  "Crescent Internet ToolPak",
  "Crescent",
  "discobot",
  "DittoSpyder",
  "DOC",
  "DotBot",
  "Download Ninja",
  "EasouSpider",
  "EmailCollector",
  "EmailSiphon",
  "EmailWolf",
  "EroCrawler",
  "Exabot",
  "ExtractorPro",
  "Fasterfox",
  "FeedBooster",
  "Foobot",
  "Genieo",
  "grub-client",
  "Harvest",
  "hloader",
  "httplib",
  "HTTrack",
  "humanlinks",
  "ieautodiscovery",
  "InfoNaviRobot",
  "IstellaBot",
  "Java/1.",
  "JennyBot",
  "k2spider",
  "Kenjin Spider",
  "Keyword Density/0.9",
  "larbin",
  "LexiBot",
  "libWeb",
  "libwww",
  "LinkextractorPro",
  "linko",
  "LinkScan/8.1a Unix",
  "LinkWalker",
  "LNSpiderguy",
  "lwp-trivial",
  "magpie",
  "Mata Hari",
  "MaxPointCrawler",
  "MegaIndex",
  "Microsoft URL Control",
  "MIIxpc",
  "Mippin",
  "Missigua Locator",
  "Mister PiX",
  "MJ12bot",
  "moget",
  "MSIECrawler",
  "NetAnts",
  "NICErsPRO",
  "Niki-Bot",
  "NPBot",
  "Nutch",
  "Offline Explorer",
  "Openfind data gathere",
  "Openfind",
  "panscient.com",
  "PHP/5.{",
  "ProPowerBot/2.14",
  "ProWebWalker",
  "Python-urllib",
  "QueryN Metasearch",
  "RepoMonkey",
  "RMA",
  "SemrushBot",
  "SeznamBot",
  "SISTRIX",
  "sitecheck.Internetseer.com",
  "SiteSnagger",
  "SnapPreviewBot",
  "Sogou",
  "SpankBot",
  "spanner",
  "spbot",
  "Spinn3r",
  "suzuran",
  "Szukacz/1.4",
  "Teleport Pro/1.29",
  "Teleport",
  "TeleportPro",
  "Telesoft",
  "The Intraformant",
  "TheNomad",
  "TightTwatBot",
  "Titan",
  "toCrawl/UrlDispatcher",
  "True_Robot",
  "True_Robot/1.0",
  "turingos",
  "TurnitinBot",
  "UbiCrawler",
  "UnisterBot",
  "URLy Warning",
  "VCI WebViewer VCI WebViewer Win32",
  "VCI",
  "WBSearchBot",
  "Web Downloader/6.9",
  "Web Image Collector",
  "WebAuto",
  "WebBandit",
  "WebBandit/3.50",
  "WebCopier v4.0",
  "WebCopier",
  "WebEnhancer",
  "WebmasterWorldForumBot",
  "WebReaper",
  "WebSauger",
  "Website Quester",
  "Webster Pro",
  "WebStripper",
  "WebZip",
  "Wotbox",
  "wsr-agent",
  "WWW-Collector-E",
  "Xenu",
  "yandex",
  "Zao",
  "Zeus",
  "ZyBORG",
  "coccoc",
  "Incutio",
  "lmspider",
  "memoryBot",
  "serf",
  "Unknown",
  "uptime files",
  "amoxicillin",
  "capsules",
  "kamagra",
  "buy online",
  "fluoxetine",
  "estrace",
  "pills",
  "buy price",
  "augmentin",
  "paid for",
  "purchase",
  "Internet dating",
  "Online dating",
  "How to Get Rich",
  "can you order cytotec",
  "online games",
  "online casino games",
  "order online",
  "glucophage",
  "finasteride",
  "finasteride pills",
  "amoxil",
  "waterfallmagazine.com",
  "max270.us.com",
  "ivermectin",
  "hydrochlorothiazide",
  "porn",
  "zhopec.top",
  "texnika",
  "zhopec",
  "skinali",
  "komputers",
  "hueplet",
  "avtoskorost",
  "m2.tc",
  "ebli.top",
  "thefmail",
  "pomaesa",
  "darkloft",
  "waterloo",
  "kronalink",
  "silavol",
  "bk.ru",
  "traveltofly",
  "lablecerc",
  "levskij",
  "osagoonlaynkupit",
  "osagokuzmich",
  "81.222.84.2",
  "fotoalt.ru",
  "24seks",
  "zaebun",
  "mentalfloss",
  "fruityloopsstudio",
  "otcovstvo",
  "deltamarketing",
  "tengrinews",
  "Продвижение",
  "remsanteh",
  "nethouse",
  "shopogolik",
  "altkoinhaberleri",
  "cleta",
  "Asansör",
  "Arıza Bakım",
  "Montaj",
  "Mühendislik",
  "Hizmetleri",
  "vermektedir",
  "Bireyin",
  "psikolojik",
  "sağlığıyla",
  "ilgilenen",
  "tıpta",
  "uzmanlık",
  "alanıdır",
  "Psikiyatristler",
  "gerekli",
  "durumlarda",
  "ihtiyaç",
  "durumuna",
  "göre",
  "ilaç",
  "psikoterapi",
  "yalnızca",
  "uygulayabilen",
  "hekimlerdir",
  "Uzun",
  "yıllardan",
  "sizlere",
  "Türkiye",
  "Meyve-Sebze",
  "Komisyoncuları",
  "tanıtım",
  "kataloğunu",
  "çıkartarak",
  "hizmet",
  "Tanrıverdi",
  "Tarım",
  "olarak",
  "hizmeti",
  "üzerinden",
  "ettirmekteyiz",
  "20bet",
  "podiumcafe.com",
  "gamespot.com",
  "imdb.com",
  "hb-themes.com",
  "sounderatheart.com",
  "silverandblackpride.com",
  "weddingbee.com",
  "athleticsnation.com",
  "blogspot.com",
  "wiwoch.com",
  "getnoc.com",
  "hottimeinoldtown.com",
  "mamabuluo.ca",
  "openstreetmap.org",
  "bluebirdbanter.com",
  "Вперед",
  "новым",
  "приключениям",
  "откройте",
  "мир",
  "нашими",
  "турами",
  "gam32.com",
  "stoklert76.com",
  "domob.com",
  "ezgrill.com",
  "topr.com",
  "autoportal",
  "vsigo.cn",
  "Промышленные",
  "принтеры",
  "3д",
  "принтер",
  "промышленный",
  "promka",
  "samoylovaoxana",
  "mailcos",
  "Ещё",
  "можно",
  "Zeleniymis",
  "scamperly",
  "poochta",
  "rabochie",
  "zanaflex",
  "pigmentnye",
  "мощности",
  "livemintnewstoday",
  "maltanewstime",
  "mirrornewstoday",
  "nationalposttoday",
  "neatherlandnewstoday",
  "neweuropetoday",
  "chinaworldnewstoday",
  "chroniclenewstoday",
  "cnbcnewstoday",
  "cnnworldtoday",
  "crunchbasenewstoday",
  "dailyexpressnewstoday",
  "norwaynewstoday",
  "ramanuzam",
  "theheraldnewstoday",
  "theindependentnewstoday",
  "theirishtimesnewstoday",
  "theirishtimestoday",
  "themetronewstoday",
  "themirrornewstoday",
  "dzonothoan",
  "alumin",
  "ferrous",
  "upcycle",
  "Срочно",
  "Требуются",
  "djob",
  "whatsapp.com",
  "desuza",
  "dailymirrornewstoday",
  "dailystarnewstoday",
  "dailytelegraphnewstoday",
  "dutchnewstoday",
  "dwnewstoday",
  "europeannewstoday",
  "Введите",
  "pochemuchka",
  "nfoherbalmz",
  "ukraine",
  "koks",
  "barbariska",
  "предлагаем",
  "getgrass",
  "odessaforum",
  "medlavka",
  "fvmaily",
  "сайте",
  "быстрого",
  "выкупом",
  "квартиры",
  "alikson",
  "umnye",
  "cheloveka",
  "zhenskie",
  "lecastella",
  "medikamente",
  "mephedrone",
  "Украина",
  "spoops",
  "kokain",
  "eunews",
  "azbukivedi",
  "nytimesnewstoday",
  "oxfordnewstoday",
  "portugalnewstoday",
  "postgazettenewstoday",
  "republicofchinatoday",
  "reuterstoday",
  "manonydesuza",
  "djob_msk",
  "Начни",
  "phenylpyrimidin",
  "chimmed",
  "zaymy",
  "credit24",
  "snople",
  "lasix",
  "приобретают",
  "УСТАНАВЛИВАЕМ",
  "casodex",
  "israelodrg",
  "kaminov",
  "dymohodov",
  "Первая",
  "goldboy",
  "sobShuth",
  "kraken",
  "hevisgerd",
  "считаете",
  "bztpa",
  "Брянский",
  "xrumer23liz",
  "derhosulha",
  "Москва",
  "высокой",
  "andrw",
  "Играйте",
  "ogorod64",
  "almedinfo",
  "производство",
  "cryptaxbot",
  "rudiplomust",
  "sovetonk",
  "ceicag",
  "ministraagame",
  "autoplenka",
  "pyridium",
  "thorazine",
  "barbariska8912",
  "netmedsgoodxx",
  "zerkalo",
  "decor.com.ua",
  "romeoqdow",
  "HendrixDramma",
  "dfhdgdfe",
  "DavidBap",
  "rva2014r",
  "rambler",
  "РедМетСплав",
  "redmetsplav",
  "notreward",
  "proverok",
  "meganSaR",
  "ekskavator32",
  "bookmakers",
  "mcksbd",
  "ximchistka",
  "Проектирование",
  "kozhanoj",
  "musora",
  "xruma",
  "Хотите",
  "обновить",
  "urevic750",
  "mebeli",
  "celebrex",
  "autoclavetech",
  "MarketArchetyp",
  "portnoy",
  "msk.ru",
  "asdgenkabum",
  "biorevitalizaciyaa",
  "microzide",
  "sysprint",
  "xcksbd",
  "vinilovaya",
  "bayloritxa",
  "anmeldelse",
  "mixstuff",
  "Предлагаем",
  "lumigan",
  "ernsys",
  "contactmeasap",
  "myzh",
  "заниматься",
  "tatefkfw",
  "gasennick",
  "Забирай",
  "день",
  "второго",
  "elimmission",
  "Klicken",
  "diegomargene",
  "murnaldgek",
  "biorevitalizacia",
  "aphcwvexih",
  "Newsinlevels",
  "synaqueruji",
  "koreafurniture",
  "XRumer23liz",
  "mail3go",
  "protectica",
  "raonenc",
  "olspensorpmam",
  "pamelor",
  "provigil",
  "ogamzuinq",
  "comprar",
  "perevodom",
  "Gecnklsof",
  "микрозаймы",
  "CohenDramma",
  "gennemse",
  "websted",
  "tshome",
  "chaihanasafo",
  "aqiinorb",
  "tricechgolci",
  "turpoezdka",
  "yourdesires",
  "Алексей",
  "zavtra",
  "Michailzck",
  "Захоронение",
  "Никита",
  "Игоревич",
  "pamyat",
  "tdedchangair",
  "hvinorb",
  "Myzh4Smari",
  "quibubbna",
  "eduard",
  "sayhuite",
  "chas99",
  "взволнован",
  "Anthonykcrant",
  "Купить",
  "Кокаин",
  "Москве",
  "Ronaldakhaict",
  "robaxin",
  "ConnorDramma",
  "Дикое",
  "мясо",
  "myzh5luncof",
  "Jameslal",
  "Сергей",
  "drigu",
  "CameronFlazy",
  "cbdforcats",
  "classitaly",
  "ColeDramma",
  "novosti",
  "kontrol",
  "vozduha",
  "pesreuriachris",
  "sdiinorb",
  "KinaldNox",
  "kinaldgek",
  "Компания",
  "напрямую",
  "сотрудничает",
  "крупными",
  "производителями",
  "Evelyncoils",
  "WinaldNox",
  "Игровой",
  "комплекс",
  "Наклонная",
  "лестница",
  "площадкой",
  "MichaelaBug",
  "PatrickDramma",
  "dieser",
  "sstechnology",
  "infokam",
  "primeneniya",
  "autoginorb",
  "Интересно",
  "fccland",
  "Glenntikspamp",
  "AmbroseaMiz",
  "AbelDramma",
  "ibuprofen",
  "heungil",
  "whola",
  "tretinoineff",
  "theissing",
  "accutaneo",
  "Justinlocardy",
  "cbtbooks",
  "imigrantos",
  "costarus",
  "costavida",
  "Отказное",
  "письмо",
  "больше",
  "BraylenDramma",
  "healthndream",
  "Robertnot",
  "longinotticiq",
  "interesnoe",
  "MaximusDramma",
  "designlight",
  "tarlanoloev",
  "Josephler",
  "Поможем",
  "получить",
  "stroitel",
  "Donpax",
  "Наша",
  "компания",
  "специализируется",
  "WilliamGroma",
  "vogelforen",
  "JaxDramma",
  "hitta",
  "erikgvfq",
  "bemy",
  "Автосервис",
  "katalik76",
  "LavillAsync",
  "Pestitutoma",
  "Заказать",
  "botlab",
  "Craigwhole",
  "Hubertgrica",
  "Bohemia",
  "Darknet",
  "Drugs",
  "freeinsta",
  "Raymondemime",
  "Lorenwrarf",
  "sdac",
  "prednisonera",
  "utaletpwii",
  "Robertapexy",
  "Линзы",
  "для",
  "лазерного",
  "станка",
  "moidomiks",
  "MnoioKep",
  "Tumerliz",
  "miginorb",
  "gomarkt",
  "marbiso",
  "Лазерный",
  "уровень",
  "Бутовый",
  "jxhba",
  "primeneniye",
  "Тахеометр",
  "KeithbrupT",
  "Michaeltox",
  "atrimoney",
  "Jamiekab",
  "Lesliekat",
  "Ярославле",
  "avapro",
  "Lumekly",
  "gokseong",
  "klicka",
  "cvinorb",
  "omalol",
  "Autoshipping24",
  "prodvizhenie",
  "fmhyxarsqot",
  "pfuozxwszoa",
  "promocode",
  "komnat",
  "myagkie",
  "chfrdplapPn",
  "oborudovanija",
  "karimmassimov",
  "botox",
  "0daymusic",
  "plumbersan",
  "kreativwerkstatt",
  "kuvandyk",
  "axioma",
  "allmed",
  "xrumer23knodo",
  "cane-corso.moscow",
  "rightbliss",
  "lustrum",
  "virilia",
  "usufruct",
  "brasswire",
  "gemination",
  "libertyfintravel",
  "upxmail",
  "moscow",
  "beautylogy",
  "feedspot",
  "udalenie",
  "urna",
  "zetcasino",
  "suomi",
  "mp3name",
  "AccBulk",
  "aromabase",
  "btkhv",
  "septik",
  "mxm",
  "xrevelxr",
  "avtoznak",
  "dublikat",
  "Orb11ta",
  "s-centr-p",
  "starz",
  "kra",
  "hidemega",
  "mailsco",
  "dakotakyit",
  "lucianotiu",
  "pantip",
  "ludobro",
  "arpatech.com",
  "officialhealthchoice",
  "kotlov",
  ".ru",
  "ibrahimxyu",
  "sapog",
  "mustardinsights",
  "vngsmservices",
  "moneycube",
  "dostavka",
  "progrevavto",
  "stellazhtorg",
  "автошкола",
  "agora",
  "gen51",
  "marosha",
  "majestichealthcare",
  "mignonmuse",
  "xrust.com",
  "fuby",
  "Antrenor",
  "competiții",
  "ccc.og.it",
  "sib10",
  "syb65",
  "sib11",
  "k97ipqi",
  "elk.pl",
  "zarow.pl",
  "nehty.com",
  "valtrex365x",
  "sobaeksanrock",
  "black-widow",
  "macys.com",
  "sega.jp",
  "flseo.ru",
  "888starz.lol",
  "wts.la",
  "shoiler.co.kr",
  "easyhealthlink.top"
];


// Check if the request is for the total count of keywords
if (isset($_GET['count']) && $_GET['count'] == 1) {
  // Return the total count of keywords
  echo json_encode(count($blocked_keywords));
} else {
  // Check if the request includes offset and limit parameters
  $offset = isset($_GET['offset']) ? intval($_GET['offset']) : 0;
  $limit = isset($_GET['limit']) ? intval($_GET['limit']) : count($blocked_keywords);

  // Slice the array based on offset and limit
  $sliced_keywords = array_slice($blocked_keywords, $offset, $limit);

  // Return the sliced array of keywords
  echo json_encode($sliced_keywords);
}
